linuxserver/docker-wireguard

README.md, readme-vars.yml, root/defaults/Corefile
=> update Corefile to use resolv.conf

.github/workflows/greetings.yml, .github/workflows/stale.yml, Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, Jenkinsfile, README.md, readme-vars.yml, root/app/add-peer, root/etc/cont-init.d/30-config
=> replace resolvconf with openresolv

readme-vars.yml
Added a small section explaining maintaining local access to attached services
=> Maintaining local access to attached services

Jenkinsfile, README.md, readme-vars.yml, root/etc/cont-init.d/30-config
~~needs testing~~ tested, working
closes #95
=> change ip when subnet changes

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml
=> switch to iptables-legacy, update formatting

readme-vars.yml
=> Add Alpine branch

Jenkinsfile, jenkins-vars.yml
=> Mark alpine branch as prerelease

root/etc/s6-overlay/s6-rc.d/init-wireguard-module/run
=> Fix capsh logic

root/etc/s6-overlay/s6-rc.d/init-wireguard-module/run
=> Flag when wg module is built

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, root/etc/s6-overlay/s6-rc.d/init-wireguard-confs/run
* Remove duplicate `bc`, add GNU `grep`
* Mostly formatting and consistent `if` style changes to wireguard-confs
* Replace a bunch of redundant `cat`s & `echo`s that were used with grep/sed
* Remove unused PEERS_COUNT
* Use lsiown
* Allow undocumented override of USE_COREDNS
Tested as thoroughly as I can with different scenarios locally, but probably needs more eyes on.
=> Remove bc, add GNU grep, address formatting, ifs, etc.

root/etc/s6-overlay/s6-rc.d/init-wireguard-confs/run
The same as #239 but for master.
=> Address shellcheck, formatting, ifs, etc.

readme-vars.yml
=> Deprecate alpine branch

Jenkinsfile, README.md, readme-vars.yml
=> Add readme note about iptables modules

Dockerfile, Dockerfile.aarch64, readme-vars.yml
=> Revert to 3.17 base

root/etc/s6-overlay/s6-rc.d/init-wireguard-confs/run
=> Fix coredns env logic

Dockerfile, Dockerfile.aarch64
=> Remove unnecessary packages

Dockerfile, Dockerfile.aarch64
qrencode binaries have been moved to -tools package: https://git.alpinelinux.org/aports/commit/community/libqrencode?h=3.19-stable&id=a1950cf60be05044928898ebd2d436a52eaa6825
=> Install libqrencode-tools package for binaries

Dockerfile, Dockerfile.aarch64, readme-vars.yml
Because the busybox modprobe utility is unable to load zstd compressed modules.
Closes: #343
Install kmod from the alpine repository to get a more capable `modprobe` utility.
#343 
See the reproduce steps on #343
=> Install kmod from alpine repository

readme-vars.yml, root/defaults/Corefile
=> Add `errors` plugin to corefile for troubleshooting issues

readme-vars.yml
=> Add cap descriptions

readme-vars.yml
=> Deprecate legacy branch (legacy)
